const jkood = {
      
  KayitYetkilisi: "814469200671932427", //BURAYA KAYIT YETKİLİSİ GİRİLECEK
  CinsiyetsizKayıtVerilecekRol: "842126054084444180", //BURAYA NORMAL KAYITTA VERİLECEK ÜYE ROLÜ GİRİLECEK
  ErkekRol: "842112535490854972", //BURAYA ERKEK ROL GİRİLECEK
  KadınRol: "842112614770409542", //BURAYA KADIN ROL GİRİLECEK
  kayıtsızrol: "843069320049459241", //BURAYA KAYITSIZ ROL GİRİLECEK
  Kayıtkanal: "814938089575022602", //BURAYA KAYIT KANALI GİRİLECEK
  
  viprol: "843485469769072670", //BURAYA VİP ROL GİRİLECEK
  tag: "", //BURAYA TAG GİRİLECEK
  
  erkekdiger: [], //ERKEK KAYITTA VERİLECEK DİĞER ROLLERİN İD YAZIN ÖRNEĞİN; ["İD1"] VEYA ["İD1","İD2"] ŞEKLİNDE ÇOĞALTABİLİRSİNİZ.
  kızdiger: [], //KADIN KAYITTA VERİLECEK DİĞER ROLLERİN İD YAZIN ÖRNEĞİN; ["İD1"] VEYA ["İD1","İD2"] ŞEKLİNDE ÇOĞALTABİLİRSİNİZ.
  
  erkekalinacakdiger: [], //ERKEK KAYITTA ALINACAK DİĞER ROLLERİN İD YAZIN ÖRNEĞİN; ["İD1"] VEYA ["İD1","İD2"] ŞEKLİNDE ÇOĞALTABİLİRSİNİZ.
  kızalinacakdiger: [], //KADIN KAYITTA ALINACAK DİĞER ROLLERİN İD YAZIN ÖRNEĞİN; ["İD1"] VEYA ["İD1","İD2"] ŞEKLİNDE ÇOĞALTABİLİRSİNİZ.
  
  Eskiİsimler: "10", //BURAYI KURCALAMAYIN SİZE BİR ZARARI OLMAZ (PROFİL SİSTEMİNDEKİ MAX GÖSTERECEĞİ ESKİ İSİM SAYISI DEĞİŞTİRMEYİN BURAYI)
  KayitTarihi: "10", //BURAYI KURCALAMAYIN SİZE BİR ZARARI OLMAZ (PROFİL SİSTEMİNDEKİ MAX GÖSTERECEĞİ KAYIT TARİH SAYISI DEĞİŞTİRMEYİN BURAYI)
  kayitedenler: "10" //BURAYI KURCALAMAYIN SİZE BİR ZARARI OLMAZ (PROFİL SİSTEMİNDEKİ MAX GÖSTERECEĞİ KAYIT EDENLER SAYISI DEĞİŞTİRMEYİN BURAYI)
};

module.exports = jkood;